import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen antialiased flex flex-col"> 
        <div className="fixed top-0 left-0 right-0 h-16 z-50">
          <Navbar />
        </div>
        <div className="flex flex-1 pt-16">
          <div className="fixed top-16 left-0 w-52 h-[calc(100vh-4rem)] z-40">
            <Sidebar />
          </div>
          <main className="ml-52 flex-1 overflow-y-auto p-8 bg-gray-100">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
