
import type { Metadata } from "next";
import "./globals.css";
import LayoutContent from "./components/component/layout";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen antialiased">
          <Toaster position="top-right" toastOptions={{
            className: "text-sm"
          }}/>
        <LayoutContent>{children}</LayoutContent>
      </body>
    </html>
  );
}

