import type { Metadata } from "next";
import "./globals.css";
import LayoutContent from "./components/component/layout";
import AuthWrapper from "./components/Authwraper";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen antialiased">
        <Toaster position="top-right" toastOptions={{
          className: "text-sm"
        }} />
        <AuthWrapper>
          <LayoutContent>
            {children}
          </LayoutContent>
        </AuthWrapper>
      </body>
    </html>
  );
}


//  return (
//     <html lang="en">
//       <body className="h-screen antialiased">
//         <Toaster position="top-right" />
//         <AuthWrapper>
//           <LayoutContent>
//             {children}
//           </LayoutContent>
//         </AuthWrapper>
//       </body>
//     </html>
//   );